---
# --------------------------------------------------------------------------------
# Sanity check
# --------------------------------------------------------------------------------
- name: windows features sanity check
  block:
    - name: Retrieve existing windows features
      include_tasks: 00-get-windowsfeatures.yml

    - name: Check missing expected features
      include_tasks: 03-assert.yml
      vars:
        features_references: '{{ windows_features_current_list }}'
        features_to_check:   '{{ windows_features_expected_list  }}'
        error_message:       'Missing expected feature'

    - name: Check Unexpected features
      include_tasks: 03-assert.yml
      vars:
        features_references: '{{ windows_features_expected_list }}'
        features_to_check:   '{{ windows_features_current_list  }}'
        error_message:       'Found unexpected feature'

    - name: Fail if windows features have errors
      fail:
        msg: "Windows features are not in the desired state"
      when: windows_features_error_list | default([]) | length > 0

  tags:
    - sanity_check
    - sanity_check_windows_features
