trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    include:
    - roles/windows_features/*
    - builds/*
    exclude:
    - /**/*.md

jobs:
- job: BuildPackage
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:

  - task: UsePythonVersion@0
    inputs:
        versionSpec: '2.7'
        architecture: 'x64'

  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'Visual Studio Enterprise (62177529-73f0-4e11-a584-5d3526dc6999)'
      keyVaultName:  'mesfVault'
      secretsFilter: 'SQLPassword'

  # Azure CLI
  # Run Azure CLI commands against an Azure subscription in a Shell script when runnning on Linux agent or Batch script when running on Windows agent.
  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Visual Studio Enterprise (62177529-73f0-4e11-a584-5d3526dc6999)'
      scriptLocation: 'inlineScript'
      #scriptPath: # Required when scriptLocation == ScriptPath
      inlineScript: 'echo $(SQLPassword); az account list'
      #arguments: # Optional
      #addSpnToEnvironment: false # Optional
      #useGlobalConfig: false # Optional
      #workingDirectory: # Optional
      #failOnStandardError: false # Optional

  - task: Bash@3
    inputs:
        targetType: 'inline'
        script: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install virtualenv
          python -m virtualenv my_env
          source my_env/bin/activate
          python -m pip install molecule docker
          pip2 install ansible[azure]
          pip2 install docker-py
          sudo apt-get install dos2unix
    displayName: 'Install tools'

  - task: Bash@3
    inputs:
        targetType: 'inline'
        workingDirectory: roles/windows_features
        script: |
          find roles/windows_features/ -type f -not -path '*/\.*' -exec grep -Il '.' {} \; | xargs -d '\n' -L 1 dos2unix -k
    displayName: 'Convert files dos2unix'

  - task: Bash@3
    inputs:
        targetType: 'inline'
        workingDirectory: roles/windows_features
        script: |
          source ../../my_env/bin/activate
          molecule lint -s azure
    displayName: 'Molecule lint'

  - task: Bash@3
    inputs:
        targetType: 'inline'
        workingDirectory: roles/windows_features
        script: |
          source ../../my_env/bin/activate
          molecule --debug create  -s azure
    displayName: 'Create test infrastructure'

  - task: Bash@3
    inputs:
        targetType: 'inline'
        workingDirectory: roles/windows_features
        script: |
          source ../../my_env/bin/activate
          molecule converge -s azure
    displayName: 'Execute windows_features roles'
