---
# --------------------------------------------------------------------------------
# Get windows users and register the result
# --------------------------------------------------------------------------------
- name: Get windows users and register the result
  block:
    - name: Retrieve Local Users
      win_shell: Get-LocalUser | ConvertTo-Json
      register: get_local_user_results
      changed_when: false

    - name: Set Local Users facts
      set_fact:
        windows_authorization_users_status: '{{ get_local_user_results.stdout |default("[]") | from_json }}'

    - name: Display Local Users
      debug:
        var:       windows_authorization_users_status
        verbosity: '{{ windows_authorization_diagnostic_level_debug }}'
