---
# tasks file for linux_docker


# docker thin-pool

#RHEL 7.3 error on azure : [Errno 14] curl#58 - "SSL peer rejected your certificate as expired.
# sudo yum update -y --disablerepo='*' --enablerepo='*microsoft*'

## Install prerequisites : https://computingforgeeks.com/install-docker-ce-on-rhel-7-linux/
- name: Install prerequisites
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

## COnfigure LVM : https://docs.microsoft.com/fr-fr/previous-versions/azure/virtual-machines/linux/configure-lvm
# Display Disk : sudo fdisk -l
# Create Physical : sudo pvdisplay, sudo pvs, pvcreate

- name: check if the device has partition layout
  command: sfdisk -d {{ docker_storage_thinpool_device_name }}
  register: partition_layout

- debug: var=partition_layout

- name: Create or resize a volume group on top of /dev/sdb1 and /dev/sdc5.
  lvg:
    vg:  data-vg-docker
    pvs: /dev/sdc