---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: lxtest1
    ip: ''
    resource_group_name:              'ut_automation'
    location:                         'westeurope'
    virtual_network_name:             'ut_automation_vnet'
    virtual_network_address_prefixes: '10.10.0.0/16'
    subnet_name:                      'ut_automation_subnet'
    subnet_address_prefix_cidr:       '10.10.1.0/24'
    storage_name:                     'utautomationstorage'
    groups:
      - docker
provisioner:
  name: ansible
  log: true

verifier:
  name: ansible
